### ISSUE TITLE
added one more extension in end of file 

### ISSUE THREAD

**Issue by birjubhatt** [alirezat775/downloader#1]
i am using this library ...all work is good but when show the download file that time one more extension in end of file 

means when i download your url "https://s3-us-west-2.amazonaws.com/uw-s3-cdn/wp-content/uploads/sites/6/2017/11/04133712/waterfall.jpg"

that time i get in suacess download "waterfall.jpg.jpeg"

 this also same as pdf files  ...pdf file output is  ".pdf.pdf"

![Screenshot 2019-06-27 at 11 38 55 AM](https://user-images.githubusercontent.com/21102131/60241473-015d7680-98d1-11e9-8de6-ebc339799cbb.png)

**Comment by alirezat775** [comment]
thanks for report this issue, I will fix in next release.

**Comment by alirezat775** [comment]
fixed, please use version 1.0.2
