### ISSUE TITLE
Download Fails because of file name length

### ISSUE THREAD

**Issue by kelvinkioko** [alirezat775/downloader#5]
Noted that some of my downloads were failing because the autogenerated file name was too long.

I was able to trace the source of the issue to the 'DownloadTask.kt' file. After some tries I updated the code on my end to 

/**
 * Added the name string checker to make sure the 'file is too long' exception doesn't happen again
*/
            fileName = when {
                fileName == null -> System.currentTimeMillis().toString()
                fileName.toString().length > 20 -> cleanName()
                else -> fileName
            }

private fun cleanName(): String{
        return DatabaseApp().getDownloadsDao(context.get()!!.applicationContext).getDownloadByUrl(url).name
            .replace("[VIDEO ONLY]", "").replace("[AUDIO ONLY]", "").substring(0, 25)
    }

This checks the filename size and the cleanName creates a 25 character name to append to the file

**Comment by alirezat775** [comment]
Hi @kelvinkioko, I will check it so, you can set name directly with
```
downloader.fileName(fileName, fileExtension)
```

**Comment by alirezat775** [comment]
can you send the URL?
